import time
import base64
import asyncio
import aiohttp
import discord

from PIL import Image
from io import BytesIO
from discord import app_commands
from discord.ext import commands

class Dropdown(discord.ui.Select):
    def __init__(self, message, images, user):
        self.message = message
        self.images = images
        self.user = user

        options = [
            discord.SelectOption(label="1"),
            discord.SelectOption(label="2"),
            discord.SelectOption(label="3"),
            discord.SelectOption(label="4"),
            discord.SelectOption(label="5"),
            discord.SelectOption(label="6"),
            discord.SelectOption(label="7"),
            discord.SelectOption(label="8"),
            discord.SelectOption(label="9"),   
        ]

        super().__init__(
            placeholder="Select the image you'd like to view:",
            min_values=1,
            max_values=9,
            options=options
        )
    
    async def callback(self, interaction: discord.Interaction):
        if not int(self.user) == int(interaction.user.id):
            await interaction.response.send_message("Unfortanately you are not the author of this command.", ephemeral=True)
        selection = int(self.values[0]) - 1
        image = BytesIO(base64.decodebytes(self.images[selection].encode("utf-8")))
        await self.message.edit(content="Images generated by **craiyon.com**.\n⚠️Certain images including human beings can be extremely gruesome and horrifing.", attachments=discord.File(image, 
        "generatedImage.png"), view=DropdownView(self.message, self.images, self.user))

class DropdownView(discord.ui.View):
    def __init__(self, message, images, user):
        super().__init__()
        self.message = message
        self.images = images
        self.user = user
        self.add_item(Dropdown(self.message, self.images, self.user))


class Image(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    @commands.command(name='generate', description='Generate 9 images from a given prompt')
    async def _generate(self, ctx: commands.Context, *, prompt: str):
        eta = int(time.time() + 60)
        msg = await ctx.reply(f"Generating images based off of the given prompt....ETA: <t:{eta}:R>")
        async with aiohttp.request("POST", "https://backend.craiyon.com/generate", json={"prompt": prompt}) as resp:
            r = await resp.json()
            images = r['images']
            image = BytesIO(base64.decodebytes(images[0].encode("utf-8")))
            await msg.edit(content="Images generated by **craiyon.com**.\n⚠️Certain images including human beings can be extremely gruesome and horrifing.", attachments=discord.File(image, 
            "generatedImage.png"), view=DropdownView(msg, images, ctx.author.id))


async def setup(bot):
    await bot.add_cog(
        Image(bot),
        guilds = [discord.Object(id = 1037005626112491522), discord.Object(id = 924924186697281567)]
    )
